### ISSUE TITLE
Need help?

### ISSUE THREAD

**Issue by tedvanderveen** [laurentenhoor/devdigger#1]
Hi @laurentenhoor! Judging only by the name of this repo, it sounds like a very cool project. Are you looking for peers to help develop this? Groeten ;)

**Comment by laurentenhoor** [comment]
Hi @tedvanderveen! Yes, let's collaborate! I have some rough ideas for this project but didn't write them down yet. Do you want to join me in this exercise?

**Comment by tedvanderveen** [comment]
Yes, sure sounds interesting! I shall send you a DM via LinkedIn
